import React, { useEffect, useMemo, useState } from 'react';
import './App.css';

const companies = [
  { ticker: 'NBIS', name: 'Nebius Group', price: '34.82', change: '-2.8%', emotion: 39, fundamentals: 83, exposure: 92, gap: 'Positive', color: '#ffb45d' },
  { ticker: 'CRWV', name: 'CoreWeave', price: '71.44', change: '+1.6%', emotion: 66, fundamentals: 76, exposure: 94, gap: 'Elevated', color: '#6fa9ff' },
  { ticker: 'ORCL', name: 'Oracle', price: '186.25', change: '+0.4%', emotion: 58, fundamentals: 71, exposure: 68, gap: 'Balanced', color: '#b787ff' },
  { ticker: 'AVGO', name: 'Broadcom', price: '294.61', change: '+1.1%', emotion: 72, fundamentals: 81, exposure: 62, gap: 'Elevated', color: '#5de0bd' },
];
const evidence = [
  { type: 'POWER', title: 'PJM load forecast revised higher through 2030', impact: '+', detail: 'Grid readiness · Mid-Atlantic', source: 'PJM Load Forecast', time: '2h ago' },
  { type: 'PERMIT', title: '310 MW campus receives zoning approval in Virginia', impact: '+', detail: 'Project velocity · Northern Virginia', source: 'County planning record', time: '6h ago' },
  { type: 'CONSTRAINT', title: '800 MW delivery schedule moves beyond 2028', impact: '−', detail: 'Interconnection delay · Texas', source: 'Utility filing', time: '1d ago' },
  { type: 'CAPEX', title: 'OCI capacity investment guidance increased', impact: '+', detail: 'Corporate investment · Oracle', source: 'Company earnings release', time: '2d ago' },
];
const regions = [
  { name: 'Northern Virginia', grid: 'PJM', planned: '2.4 GW', secured: '1.1 GW', friction: 62, note: 'Transmission queue pressure', x: 63, y: 31 },
  { name: 'Texas', grid: 'ERCOT', planned: '3.2 GW', secured: '1.7 GW', friction: 71, note: 'Delivery timing revised', x: 34, y: 64 },
  { name: 'Arizona', grid: 'WECC', planned: '1.1 GW', secured: '0.6 GW', friction: 44, note: 'Water review monitored', x: 19, y: 58 },
  { name: 'Ohio', grid: 'PJM', planned: '0.9 GW', secured: '0.5 GW', friction: 38, note: 'Approvals progressing', x: 55, y: 43 },
];
function Ring({ value, label, tone = 'blue' }) { return <div className={`ring ${tone}`} style={{ '--score': `${value * 3.6}deg` }}><div><strong>{value}</strong><span>/100</span><small>{label}</small></div></div>; }
function App() {
  const [period, setPeriod] = useState('30D'); const [ticker, setTicker] = useState('NBIS'); const [filter, setFilter] = useState('All evidence'); const [weights, setWeights] = useState(false); const [weight, setWeight] = useState(100); const [view, setView] = useState('Overview'); const [region, setRegion] = useState('Northern Virginia'); const [apiState, setApiState] = useState('demo');
  useEffect(() => { let active = true; fetch('/api/health').then(response => response.ok ? response.json() : Promise.reject()).then(payload => { if (active) setApiState(Object.values(payload.sources || {}).some(item => item.status === 'ok') ? 'live' : 'degraded'); }).catch(() => { if (active) setApiState('demo'); }); return () => { active = false; }; }, []);
  const active = companies.find(c => c.ticker === ticker); const filtered = useMemo(() => filter === 'All evidence' ? evidence : evidence.filter(e => e.type === filter), [filter]); const expansion = Math.round(76 * weight / 100);
  return <main className="shell">
    <header><div className="brand"><i>◫</i><div><b>GRIDLINE</b><small>INFRASTRUCTURE INTELLIGENCE</small></div></div><nav>{['Overview','Infrastructure','Events','Methodology'].map(item=><button key={item} onClick={()=>setView(item)} className={view===item?'current':''}>{item}</button>)}</nav><div className="head-actions"><span className={`live ${apiState}`}>{apiState === 'live' ? 'Live data' : apiState === 'degraded' ? 'Source check needed' : 'Demo snapshot'}</span><button className="key">⌘ K</button><button className="avatar">MK</button></div></header>
    {view === 'Overview' && <>
    <section className="hero"><div><p className="eyebrow">MARKET INTELLIGENCE / US DATA CENTER BUILDOUT</p><h1>Data center buildout,<br/><em>made inspectable.</em></h1><p className="copy">Physical capacity, power delivery, regulation and market expectations—connected to the evidence behind every signal.</p></div><div className="asof"><span>AS OF</span><b>SEP 15, 2026 · 09:42 ET</b><small>12 sources refreshed in the last 24 hours</small></div></section>
    <section className="regime"><div className="regime-name"><span className="pulse">●</span><div><p className="eyebrow">DC BUILDOUT REGIME</p><h2>EXPANDING <em>— BUT CONSTRAINED</em></h2><p>Demand remains durable; power delivery is increasingly the limiting variable.</p></div></div><div className="regime-scores"><div><Ring value={expansion} label="EXPANSION" tone="amber"/><p>+5 <small>vs 30D</small></p></div><div><Ring value={58} label="PUSHBACK" tone="coral"/><p>+14 <small>vs 30D</small></p></div></div><div className="regime-buttons"><button onClick={() => setWeights(!weights)}>⚙ Methodology weights</button><button className="primary">Explore the regime →</button></div></section>
    {weights && <section className="weights"><div><b>Capacity momentum weight</b><small>Adjusts the illustrative expansion score locally.</small></div><input aria-label="Capacity momentum weight" type="range" min="40" max="130" value={weight} onChange={e => setWeight(+e.target.value)}/><output>{weight}%</output><button onClick={() => setWeight(100)}>Reset defaults</button></section>}
    <Section title="What changed the picture" label="REGIME DRIVERS" action="View all events →"/><section className="drivers">{[['↗','CAPACITY MOMENTUM','+1.2 GW','New power capacity secured','amber'],['⌁','PROJECT VELOCITY','+310 MW','Approved this week','blue'],['!','GRID FRICTION','−800 MW','Delivery delayed','red'],['◌','REGULATORY PRESSURE','2','New restrictions proposed','purple']].map(x=><article key={x[1]}><span className={`driver-icon ${x[4]}`}>{x[0]}</span><p className="label">{x[1]}</p><strong>{x[2]}</strong><small>{x[3]}</small><div className={`bars ${x[4]}`}>{[22,40,32,65,48,82,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article>)}</section>
    <section className="section company-title"><div><p className="eyebrow">EXPOSURE MONITOR</p><h3>Where the regime matters</h3></div><div className="segmented">{['30D','90D','1Y'].map(p=><button key={p} onClick={()=>setPeriod(p)} className={period===p?'selected':''}>{p}</button>)}</div></section>
    <section className="companies">{companies.map(c=><button className={`company ${ticker===c.ticker?'selected-card':''}`} onClick={()=>setTicker(c.ticker)} key={c.ticker}><div className="company-top"><div><b>{c.ticker}</b><small>{c.name}</small></div><span className={c.change[0]==='-'?'negative':'positive'}>{c.change}</span></div><strong className="price">${c.price}</strong><div className="stat"><span>MARKET EMOTION <b>{c.emotion}</b></span><span>FUNDAMENTALS <b>{c.fundamentals}</b></span></div><div className="exposure"><span>DC EXPOSURE</span><div><i style={{width:`${c.exposure}%`,background:c.color}}/></div><b>{c.exposure}</b></div><div className="gap"><span>EXPECTATIONS GAP</span><b>{c.gap} ↗</b></div></button>)}</section>
    <section className="bottom"><article className="thesis"><PanelTitle label="SELECTED SETUP" title={`${active.ticker} / ${period} view`} extra="● 86% DATA CONFIDENCE"/><div className="thesis-content"><Ring value={active.fundamentals} label="FUNDAMENTALS"/><div><h4>Potential positive dislocation</h4><p>Direct AI capacity exposure remains high while market emotion has reset. The key dependency is verified power delivery against planned capacity.</p><button className="text">Inspect {active.ticker} evidence →</button></div></div><div className="signals"><span>PHYSICAL SIGNAL <b>Improving</b></span><span>MARKET SIGNAL <b className="negative">Cautious</b></span><span>VALUATION <b>55th percentile</b></span></div></article><article className="ledger"><div className="panel-title"><div><p className="eyebrow">EVIDENCE LEDGER</p><h3>Raw signals, not sentiment</h3></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All evidence</option><option>POWER</option><option>PERMIT</option><option>CONSTRAINT</option><option>CAPEX</option></select></div><div>{filtered.map(e=><div className="event" key={e.title}><span className={`impact ${e.impact==='+'?'up':'down'}`}>{e.impact}</span><div><p><b>{e.type}</b> · {e.time}</p><h4>{e.title}</h4><small>{e.detail} · {e.source}</small></div><span className="quality">PRIMARY</span></div>)}</div></article></section>
    </>}
    {view === 'Infrastructure' && <Infrastructure region={region} setRegion={setRegion}/>}
    {view === 'Events' && <Events filter={filter} setFilter={setFilter}/>}
    {view === 'Methodology' && <Methodology/>}
    <footer><span>DATA IS POINT-IN-TIME · SCORES ARE DETERMINISTIC · NOT INVESTMENT ADVICE</span><span>Sources: PJM · EIA · FERC · SEC EDGAR · Company IR</span></footer>
  </main>;
}
function Section({label,title,action}) { return <section className="section"><div><p className="eyebrow">{label}</p><h3>{title}</h3></div><button className="text">{action}</button></section>; }
function PanelTitle({label,title,extra}) { return <div className="panel-title"><div><p className="eyebrow">{label}</p><h3>{title}</h3></div><span className="confidence">{extra}</span></div>; }
function Infrastructure({ region, setRegion }) { const selected = regions.find(item => item.name === region); return <section className="view-page"><p className="eyebrow">INFRASTRUCTURE / CAPACITY AND CONSTRAINTS</p><h1>Buildout has a<br/><em>physical address.</em></h1><p className="copy">Track planned, secured and delayed capacity through the grid regions where it must actually be delivered.</p><div className="infrastructure-grid"><article className="map-panel"><div className="panel-title"><div><p className="eyebrow">GEOGRAPHIC CONSTRAINT MAP</p><h3>US data center pipeline</h3></div><span className="confidence">● CURATED MVP</span></div><div className="usa-map">{regions.map(item=><button aria-label={`Select ${item.name}`} key={item.name} onClick={()=>setRegion(item.name)} className={`map-dot ${region===item.name?'active-dot':''}`} style={{left:`${item.x}%`,top:`${item.y}%`}}><i></i><span>{item.name}</span></button>)}<b>US GRID REGIONS</b></div><div className="map-legend"><span><i className="operating"></i> Operating / secured</span><span><i className="constrained"></i> Constraint monitored</span><span><i className="delayed"></i> Material delay</span></div></article><article className="region-detail"><p className="eyebrow">SELECTED REGION</p><h2>{selected.name} <em>/ {selected.grid}</em></h2><p>{selected.note}</p><div className="metric-stack"><div><span>PLANNED PIPELINE</span><b>{selected.planned}</b></div><div><span>POWER SECURED</span><b>{selected.secured}</b></div><div><span>PUSHBACK INDEX</span><b className={selected.friction > 60 ? 'negative' : 'positive'}>{selected.friction}/100</b></div></div><button className="primary">Inspect regional evidence →</button></article></div><section className="section"><div><p className="eyebrow">REGIONAL QUEUE</p><h3>Projects awaiting a change in status</h3></div><button className="text">Filter all regions →</button></section><div className="queue"><div className="queue-row queue-head"><span>PROJECT</span><span>OPERATOR</span><span>MW</span><span>STATUS</span><span>NEXT MILESTONE</span></div>{[['Loudoun Campus III','CRWV','310','Approved','Power study · Q4 2026'],['West Texas AI Park','NBIS','800','Delayed','ERCOT delivery review'],['Phoenix Compute Zone','ORCL','420','Power secured','Construction start · Q1 2027']].map(row=><div className="queue-row" key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===3 && cell==='Delayed'?'negative':''}>{cell}</span>)}</div>)}</div></section>; }
function Events({filter,setFilter}) { const values = ['All evidence','POWER','PERMIT','CONSTRAINT','CAPEX']; const list = filter === 'All evidence' ? evidence : evidence.filter(item => item.type === filter); return <section className="view-page"><p className="eyebrow">EVENTS / EVIDENCE DATABASE</p><h1>Every score has<br/><em>a source trail.</em></h1><p className="copy">A normalized event ledger: one event, multiple corroborating sources, and no implied signal where the evidence is uncertain.</p><div className="event-toolbar"><div>{values.map(value=><button onClick={()=>setFilter(value)} key={value} className={filter===value?'active-filter':''}>{value}</button>)}</div><span>4 of 4 evidence records</span></div><div className="event-table">{list.map(item=><article key={item.title}><span className={`impact ${item.impact==='+'?'up':'down'}`}>{item.impact}</span><div><p className="eyebrow">{item.type} · {item.time}</p><h3>{item.title}</h3><p>{item.detail}</p></div><div className="event-meta"><b>PRIMARY</b><span>{item.source}</span><button className="text">View record →</button></div></article>)}</div></section>; }
function Methodology() { return <section className="view-page methodology"><p className="eyebrow">SCORING / TRANSPARENT BY DESIGN</p><h1>No black-box<br/><em>bullishness score.</em></h1><p className="copy">The regime combines verifiable operational observations. News may create a candidate record, but it cannot override a primary source.</p><div className="method-grid">{[['01','Expansion Index','Capacity momentum 35% · Corporate investment 25% · Grid readiness 20% · Project velocity 20%'],['02','Pushback Index','Delayed MW 35% · Grid friction 25% · Regulation 20% · Local and financing friction 20%'],['03','Confidence','Source quality, corroboration, entity certainty and freshness all remain visible.'],['04','Expectations Gap','Physical and fundamental signal compared with market emotion and applicable valuation context.']].map(card=><article key={card[0]}><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></article>)}</div><div className="method-note"><b>Important:</b> This is decision support, not automated trading advice. Historical evaluation must use only information available at the time of each observation.</div></section>; }
export default App;
