import React, { useEffect, useMemo, useState } from 'react';
import './App.css';

const companies = [
  { ticker: 'NBIS', name: 'Nebius Group', price: '34.82', change: '-2.8%', emotion: 39, fundamentals: 83, exposure: 92, gap: 'Positive', color: '#ffb45d', irUrl: 'https://nebius.com/investor-hub' },
  { ticker: 'CRWV', name: 'CoreWeave', price: '71.44', change: '+1.6%', emotion: 66, fundamentals: 76, exposure: 94, gap: 'Elevated', color: '#6fa9ff', irUrl: 'https://investors.coreweave.com/overview/default.aspx' },
  { ticker: 'ORCL', name: 'Oracle', price: '186.25', change: '+0.4%', emotion: 58, fundamentals: 71, exposure: 68, gap: 'Balanced', color: '#b787ff', irUrl: 'https://investor.oracle.com/' },
  { ticker: 'AVGO', name: 'Broadcom', price: '294.61', change: '+1.1%', emotion: 72, fundamentals: 81, exposure: 62, gap: 'Elevated', color: '#5de0bd', irUrl: 'https://investors.broadcom.com/' },
];
const evidence = [
  { type: 'POWER', title: 'PJM load forecast revised higher through 2030', impact: '+', detail: 'Grid readiness · Mid-Atlantic', source: 'PJM Load Forecast', time: '2h ago', url: 'https://www.pjm.com/planning/resource-adequacy-planning/load-forecast-development' },
  { type: 'PERMIT', title: '310 MW campus receives zoning approval in Virginia', impact: '+', detail: 'Project velocity · Northern Virginia', source: 'Loudoun County planning', time: '6h ago', url: 'https://www.loudoun.gov/158/Planning-Zoning' },
  { type: 'CONSTRAINT', title: '800 MW delivery schedule moves beyond 2028', impact: '−', detail: 'Interconnection delay · Texas', source: 'ERCOT grid information', time: '1d ago', url: 'https://www.ercot.com/gridinfo' },
  { type: 'CAPEX', title: 'OCI capacity investment guidance increased', impact: '+', detail: 'Corporate investment · Oracle', source: 'Oracle quarterly earnings', time: '2d ago', url: 'https://investor.oracle.com/financial-information/quarterly-earnings/default.aspx' },
];
const regions = [
  { name: 'Northern Virginia', grid: 'PJM', planned: '2.4 GW', secured: '1.1 GW', friction: 62, note: 'Transmission queue pressure', x: 63, y: 31 },
  { name: 'Texas', grid: 'ERCOT', planned: '3.2 GW', secured: '1.7 GW', friction: 71, note: 'Delivery timing revised', x: 34, y: 64 },
  { name: 'Arizona', grid: 'WECC', planned: '1.1 GW', secured: '0.6 GW', friction: 44, note: 'Water review monitored', x: 19, y: 58 },
  { name: 'Ohio', grid: 'PJM', planned: '0.9 GW', secured: '0.5 GW', friction: 38, note: 'Approvals progressing', x: 55, y: 43 },
];
function Ring({ value, label, tone = 'blue' }) { return <div className={`ring ${tone}`} style={{ '--score': `${value * 3.6}deg` }}><div><strong>{value}</strong><span>/100</span><small>{label}</small></div></div>; }
function App() {
  const [period, setPeriod] = useState('30D'); const [ticker, setTicker] = useState('NBIS'); const [filter, setFilter] = useState('All evidence'); const [weights, setWeights] = useState(false); const [weight, setWeight] = useState(100); const [view, setView] = useState('Overview'); const [region, setRegion] = useState('Northern Virginia'); const [apiState, setApiState] = useState('demo'); const [language, setLanguage] = useState('en'); const zh = language === 'zh-TW'; const t = (english, chinese) => zh ? chinese : english;
  useEffect(() => { let active = true; const stateFrom = payload => Object.values(payload.sources || payload.sourceHealth || {}).some(item => item.status === 'ok') ? 'live' : Object.keys(payload.sources || payload.sourceHealth || {}).length ? 'degraded' : 'demo'; fetch('/api/health').then(response => response.ok ? response.json() : Promise.reject()).catch(() => fetch(`${process.env.PUBLIC_URL}/data/dashboard-snapshot.json`).then(response => response.ok ? response.json() : Promise.reject())).then(payload => { if (active) setApiState(stateFrom(payload)); }).catch(() => { if (active) setApiState('demo'); }); return () => { active = false; }; }, []);
  const active = companies.find(c => c.ticker === ticker); const filtered = useMemo(() => filter === 'All evidence' ? evidence : evidence.filter(e => e.type === filter), [filter]); const expansion = Math.round(76 * weight / 100);
  return <main className="shell" lang={language}>
    <header><div className="brand"><i>◫</i><div><b>GRIDLINE</b><small>{t('INFRASTRUCTURE INTELLIGENCE','基礎設施情報')}</small></div></div><nav>{['Overview','Infrastructure','Events','Methodology'].map(item=><button key={item} onClick={()=>setView(item)} className={view===item?'current':''}>{t(item, { Overview:'總覽', Infrastructure:'基礎設施', Events:'事件', Methodology:'方法論' }[item])}</button>)}</nav><div className="head-actions"><button className="language" onClick={()=>setLanguage(zh ? 'en' : 'zh-TW')} aria-label={t('Switch to Traditional Chinese','切換為英文')}>{zh ? 'EN' : '繁中'}</button><span className={`live ${apiState}`}>{apiState === 'live' ? t('Live data','即時資料') : apiState === 'degraded' ? t('Source check needed','來源需檢查') : t('Demo snapshot','示範快照')}</span><button className="key">⌘ K</button><button className="avatar">MK</button></div></header>
    {view === 'Overview' && <>
    <section className="hero"><div><p className="eyebrow">{t('MARKET INTELLIGENCE / US DATA CENTER BUILDOUT','市場情報 / 美國資料中心建設')}</p><h1>{t('Data center buildout,','資料中心建設，')}<br/><em>{t('made inspectable.','一目瞭然。')}</em></h1><p className="copy">{t('Physical capacity, power delivery, regulation and market expectations—connected to the evidence behind every signal.','實體容量、供電、法規與市場預期——每一個訊號都可追溯至其依據。')}</p></div><div className="asof"><span>{t('AS OF','截至')}</span><b>SEP 15, 2026 · 09:42 ET</b><small>{t('12 sources refreshed in the last 24 hours','12 個資料來源於過去 24 小時內更新')}</small></div></section>
    <section className="regime"><div className="regime-name"><span className="pulse">●</span><div><p className="eyebrow">{t('DC BUILDOUT REGIME','資料中心建設週期')}</p><h2>{t('EXPANDING','擴張中')} <em>{t('— BUT CONSTRAINED','— 但受限制')}</em></h2><p>{t('Demand remains durable; power delivery is increasingly the limiting variable.','需求依然強勁；供電交付日益成為關鍵限制。')}</p></div></div><div className="regime-scores"><div><Ring value={expansion} label={t('EXPANSION','擴張')} tone="amber"/><p>+5 <small>{t('vs 30D','較 30 日')}</small></p></div><div><Ring value={58} label={t('PUSHBACK','阻力')} tone="coral"/><p>+14 <small>{t('vs 30D','較 30 日')}</small></p></div></div><div className="regime-buttons"><button onClick={() => setWeights(!weights)}>⚙ {t('Methodology weights','方法論權重')}</button><button className="primary">{t('Explore the regime →','探索週期 →')}</button></div></section>
    {weights && <section className="weights"><div><b>{t('Capacity momentum weight','容量動能權重')}</b><small>{t('Adjusts the illustrative expansion score locally.','在本機調整示範用擴張分數。')}</small></div><input aria-label={t('Capacity momentum weight','容量動能權重')} type="range" min="40" max="130" value={weight} onChange={e => setWeight(+e.target.value)}/><output>{weight}%</output><button onClick={() => setWeight(100)}>{t('Reset defaults','重設預設值')}</button></section>}
    <Section title={t('What changed the picture','改變情勢的因素')} label={t('REGIME DRIVERS','週期驅動因素')} action={t('View all events →','查看所有事件 →')} onAction={()=>setView('Events')}/><section className="drivers">{[['↗',t('CAPACITY MOMENTUM','容量動能'),'+1.2 GW',t('New power capacity secured','新增已確保供電容量'),'amber'],['⌁',t('PROJECT VELOCITY','專案進度'),'+310 MW',t('Approved this week','本週獲核准'),'blue'],['!',t('GRID FRICTION','電網摩擦'),'−800 MW',t('Delivery delayed','交付延遲'),'red'],['◌',t('REGULATORY PRESSURE','法規壓力'),'2',t('New restrictions proposed','新增限制提案'),'purple']].map(x=><article key={x[1]}><span className={`driver-icon ${x[4]}`}>{x[0]}</span><p className="label">{x[1]}</p><strong>{x[2]}</strong><small>{x[3]}</small><div className={`bars ${x[4]}`}>{[22,40,32,65,48,82,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article>)}</section>
    <section className="section company-title"><div><p className="eyebrow">{t('EXPOSURE MONITOR','曝險監測')}</p><h3>{t('Where the regime matters','週期影響所在')}</h3></div><div className="segmented">{['30D','90D','1Y'].map(p=><button key={p} onClick={()=>setPeriod(p)} className={period===p?'selected':''}>{p}</button>)}</div></section>
    <section className="companies">{companies.map(c=><button className={`company ${ticker===c.ticker?'selected-card':''}`} onClick={()=>setTicker(c.ticker)} key={c.ticker}><div className="company-top"><div><b>{c.ticker}</b><small>{c.name}</small></div><span className={c.change[0]==='-'?'negative':'positive'}>{c.change}</span></div><strong className="price">${c.price}</strong><div className="stat"><span>{t('MARKET EMOTION','市場情緒')} <b>{c.emotion}</b></span><span>{t('FUNDAMENTALS','基本面')} <b>{c.fundamentals}</b></span></div><div className="exposure"><span>{t('DC EXPOSURE','資料中心曝險')}</span><div><i style={{width:`${c.exposure}%`,background:c.color}}/></div><b>{c.exposure}</b></div><div className="gap"><span>{t('EXPECTATIONS GAP','預期落差')}</span><b>{t(c.gap, { Positive:'正向', Elevated:'偏高', Balanced:'均衡' }[c.gap])} ↗</b></div></button>)}</section>
    <section className="bottom"><article className="thesis"><PanelTitle label={t('SELECTED SETUP','所選標的')} title={`${active.ticker} / ${period} ${t('view','檢視')}`} extra={`● 86% ${t('DATA CONFIDENCE','資料可信度')}`}/><div className="thesis-content"><Ring value={active.fundamentals} label={t('FUNDAMENTALS','基本面')}/><div><h4>{t('Potential positive dislocation','可能的正向錯價')}</h4><p>{t('Direct AI capacity exposure remains high while market emotion has reset. The key dependency is verified power delivery against planned capacity.','直接 AI 容量曝險仍高，但市場情緒已回落。關鍵依賴是計畫容量能否獲得已驗證的供電交付。')}</p><button className="text">{t('Inspect','檢視')} {active.ticker} {t('evidence →','證據 →')}</button></div></div><div className="signals"><span>{t('PHYSICAL SIGNAL','實體訊號')} <b>{t('Improving','改善中')}</b></span><span>{t('MARKET SIGNAL','市場訊號')} <b className="negative">{t('Cautious','審慎')}</b></span><span>{t('VALUATION','估值')} <b>{t('55th percentile','第 55 百分位')}</b></span></div></article><article className="ledger"><div className="panel-title"><div><p className="eyebrow">{t('EVIDENCE LEDGER','證據帳本')}</p><h3>{t('Raw signals, not sentiment','原始訊號，而非情緒')}</h3></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>{t('All evidence','所有證據')}</option><option>POWER</option><option>PERMIT</option><option>CONSTRAINT</option><option>CAPEX</option></select></div><div>{filtered.map(e=><div className="event" key={e.title}><span className={`impact ${e.impact==='+'?'up':'down'}`}>{e.impact}</span><div><p><b>{e.type}</b> · {e.time}</p><h4>{e.title}</h4><small>{e.detail} · {e.source}</small></div><span className="quality">{t('PRIMARY','一級來源')}</span></div>)}</div></article></section>
    </>}
    {view === 'Infrastructure' && (zh ? <InfrastructureZh region={region} setRegion={setRegion}/> : <Infrastructure region={region} setRegion={setRegion}/>)}
    {view === 'Events' && (zh ? <EventsZh filter={filter} setFilter={setFilter}/> : <Events filter={filter} setFilter={setFilter}/>)}
    {view === 'Methodology' && (zh ? <MethodologyZh/> : <Methodology/>)}
    <EvidenceLinks t={t}/>
    <footer><span>{t('DATA IS POINT-IN-TIME · SCORES ARE DETERMINISTIC · NOT INVESTMENT ADVICE','資料為時間點資料 · 分數為可驗證決定性計算 · 非投資建議')}</span><span>{t('Sources:','來源：')} PJM · EIA · FERC · SEC EDGAR · Company IR</span></footer>
  </main>;
}
function Section({label,title,action,onAction}) { return <section className="section"><div><p className="eyebrow">{label}</p><h3>{title}</h3></div><button className="text" onClick={onAction}>{action}</button></section>; }
function PanelTitle({label,title,extra}) { return <div className="panel-title"><div><p className="eyebrow">{label}</p><h3>{title}</h3></div><span className="confidence">{extra}</span></div>; }
function Infrastructure({ region, setRegion }) { const selected = regions.find(item => item.name === region); return <section className="view-page"><p className="eyebrow">INFRASTRUCTURE / CAPACITY AND CONSTRAINTS</p><h1>Buildout has a<br/><em>physical address.</em></h1><p className="copy">Track planned, secured and delayed capacity through the grid regions where it must actually be delivered.</p><div className="infrastructure-grid"><article className="map-panel"><div className="panel-title"><div><p className="eyebrow">GEOGRAPHIC CONSTRAINT MAP</p><h3>US data center pipeline</h3></div><span className="confidence">● CURATED MVP</span></div><div className="usa-map">{regions.map(item=><button aria-label={`Select ${item.name}`} key={item.name} onClick={()=>setRegion(item.name)} className={`map-dot ${region===item.name?'active-dot':''}`} style={{left:`${item.x}%`,top:`${item.y}%`}}><i></i><span>{item.name}</span></button>)}<b>US GRID REGIONS</b></div><div className="map-legend"><span><i className="operating"></i> Operating / secured</span><span><i className="constrained"></i> Constraint monitored</span><span><i className="delayed"></i> Material delay</span></div></article><article className="region-detail"><p className="eyebrow">SELECTED REGION</p><h2>{selected.name} <em>/ {selected.grid}</em></h2><p>{selected.note}</p><div className="metric-stack"><div><span>PLANNED PIPELINE</span><b>{selected.planned}</b></div><div><span>POWER SECURED</span><b>{selected.secured}</b></div><div><span>PUSHBACK INDEX</span><b className={selected.friction > 60 ? 'negative' : 'positive'}>{selected.friction}/100</b></div></div><button className="primary">Inspect regional evidence →</button></article></div><section className="section"><div><p className="eyebrow">REGIONAL QUEUE</p><h3>Projects awaiting a change in status</h3></div><button className="text">Filter all regions →</button></section><div className="queue"><div className="queue-row queue-head"><span>PROJECT</span><span>OPERATOR</span><span>MW</span><span>STATUS</span><span>NEXT MILESTONE</span></div>{[['Loudoun Campus III','CRWV','310','Approved','Power study · Q4 2026'],['West Texas AI Park','NBIS','800','Delayed','ERCOT delivery review'],['Phoenix Compute Zone','ORCL','420','Power secured','Construction start · Q1 2027']].map(row=><div className="queue-row" key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===3 && cell==='Delayed'?'negative':''}>{cell}</span>)}</div>)}</div></section>; }
function Events({filter,setFilter}) { const values = ['All evidence','POWER','PERMIT','CONSTRAINT','CAPEX']; const list = filter === 'All evidence' ? evidence : evidence.filter(item => item.type === filter); return <section className="view-page"><p className="eyebrow">EVENTS / EVIDENCE DATABASE</p><h1>Every score has<br/><em>a source trail.</em></h1><p className="copy">A normalized event ledger: one event, multiple corroborating sources, and no implied signal where the evidence is uncertain.</p><div className="event-toolbar"><div>{values.map(value=><button onClick={()=>setFilter(value)} key={value} className={filter===value?'active-filter':''}>{value}</button>)}</div><span>4 of 4 evidence records</span></div><div className="event-table">{list.map(item=><article key={item.title}><span className={`impact ${item.impact==='+'?'up':'down'}`}>{item.impact}</span><div><p className="eyebrow">{item.type} · {item.time}</p><h3>{item.title}</h3><p>{item.detail}</p></div><div className="event-meta"><b>PRIMARY</b><span>{item.source}</span><button className="text">View record →</button></div></article>)}</div></section>; }
function Methodology() { return <section className="view-page methodology"><p className="eyebrow">SCORING / TRANSPARENT BY DESIGN</p><h1>No black-box<br/><em>bullishness score.</em></h1><p className="copy">The regime combines verifiable operational observations. News may create a candidate record, but it cannot override a primary source.</p><div className="method-grid">{[['01','Expansion Index','Capacity momentum 35% · Corporate investment 25% · Grid readiness 20% · Project velocity 20%'],['02','Pushback Index','Delayed MW 35% · Grid friction 25% · Regulation 20% · Local and financing friction 20%'],['03','Confidence','Source quality, corroboration, entity certainty and freshness all remain visible.'],['04','Expectations Gap','Physical and fundamental signal compared with market emotion and applicable valuation context.']].map(card=><article key={card[0]}><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></article>)}</div><div className="method-note"><b>Important:</b> This is decision support, not automated trading advice. Historical evaluation must use only information available at the time of each observation.</div></section>; }
function InfrastructureZh({ region, setRegion }) { const selected = regions.find(item => item.name === region); return <section className="view-page"><p className="eyebrow">基礎設施 / 容量與限制</p><h1>建設週期有其<br/><em>實際所在。</em></h1><p className="copy">依據實際供電區域追蹤已規劃、已確保及延遲的容量。</p><div className="infrastructure-grid"><article className="map-panel"><div className="panel-title"><div><p className="eyebrow">地理限制地圖</p><h3>美國資料中心容量管線</h3></div><span className="confidence">● 精選 MVP</span></div><div className="usa-map">{regions.map(item=><button aria-label={`選擇 ${item.name}`} key={item.name} onClick={()=>setRegion(item.name)} className={`map-dot ${region===item.name?'active-dot':''}`} style={{left:`${item.x}%`,top:`${item.y}%`}}><i></i><span>{item.name}</span></button>)}<b>美國電網區域</b></div><div className="map-legend"><span><i className="operating"></i>營運中 / 已確保</span><span><i className="constrained"></i>限制監測中</span><span><i className="delayed"></i>重大延遲</span></div></article><article className="region-detail"><p className="eyebrow">所選區域</p><h2>{selected.name} <em>/ {selected.grid}</em></h2><p>{selected.note}</p><div className="metric-stack"><div><span>規劃容量管線</span><b>{selected.planned}</b></div><div><span>已確保供電</span><b>{selected.secured}</b></div><div><span>阻力指數</span><b className={selected.friction > 60 ? 'negative' : 'positive'}>{selected.friction}/100</b></div></div><button className="primary">檢視區域證據 →</button></article></div></section>; }
function EventsZh({filter,setFilter}) { const values = [['All evidence','所有證據'],['POWER','供電'],['PERMIT','許可'],['CONSTRAINT','限制'],['CAPEX','資本支出']]; const list = filter === 'All evidence' ? evidence : evidence.filter(item => item.type === filter); return <section className="view-page"><p className="eyebrow">事件 / 證據資料庫</p><h1>每一個分數都有<br/><em>來源軌跡。</em></h1><p className="copy">標準化事件帳本：一個事件、多個佐證來源；證據不確定時不建立暗示性訊號。</p><div className="event-toolbar"><div>{values.map(([value,label])=><button onClick={()=>setFilter(value)} key={value} className={filter===value?'active-filter':''}>{label}</button>)}</div><span>{list.length} 筆證據紀錄</span></div><div className="event-table">{list.map(item=><article key={item.title}><span className={`impact ${item.impact==='+'?'up':'down'}`}>{item.impact}</span><div><p className="eyebrow">{item.type} · {item.time}</p><h3>{item.title}</h3><p>{item.detail}</p></div><div className="event-meta"><b>一級來源</b><span>{item.source}</span><button className="text">查看紀錄 →</button></div></article>)}</div></section>; }
function MethodologyZh() { const cards = [['01','擴張指數','容量動能 35% · 公司投資 25% · 電網就緒度 20% · 專案進度 20%'],['02','阻力指數','延遲 MW 35% · 電網摩擦 25% · 法規 20% · 地方及融資摩擦 20%'],['03','可信度','來源品質、交叉佐證、實體辨識確定性及資料新鮮度均清楚揭露。'],['04','預期落差','比較實體與基本面訊號、市場情緒及適用的估值脈絡。']]; return <section className="view-page methodology"><p className="eyebrow">評分 / 透明設計</p><h1>沒有黑箱式<br/><em>看多分數。</em></h1><p className="copy">週期判斷由可驗證的營運觀察組成。新聞可以產生待驗證紀錄，但無法覆蓋一級來源。</p><div className="method-grid">{cards.map(card=><article key={card[0]}><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></article>)}</div><div className="method-note"><b>重要：</b>本工具為決策輔助，並非自動交易或投資建議。歷史評估只可使用當時已知的資訊。</div></section>; }
function EvidenceLinks({ t }) { return <section className="source-links"><div><p className="eyebrow">{t('SOURCE & COMPANY LINKS','來源與公司連結')}</p><h3>{t('Open the underlying record','開啟原始來源')}</h3></div><div>{evidence.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.title}>{item.source} ↗</a>)}{companies.map(company=><a href={company.irUrl} target="_blank" rel="noreferrer" key={company.ticker}>{company.ticker} {t('Investor Relations','投資人關係')} ↗</a>)}</div></section>; }
export default App;
